### ISSUE TITLE
Home page image

### ISSUE THREAD

**Issue by gseals** [nss-evening-cohort-10/foundations-group-project-huggy-bears#1]

**Comment by rarceneaux** [comment]
![image](https://user-images.githubusercontent.com/40898992/64911776-a5dea000-d6eb-11e9-959f-534c3e760dc7.png)

**Comment by rarceneaux** [comment]
![image](https://user-images.githubusercontent.com/40898992/64911800-0968cd80-d6ec-11e9-8ab3-3c99294ef675.png)

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/64912837-8e5ae380-d6fa-11e9-9c38-13ceac185c3e.png)
