### ISSUE TITLE
Members --Loop

### ISSUE THREAD

**Issue by maggieisgreene** [nss-evening-cohort-10/foundations-group-project-huggy-bears#10]
# User Story
As a user, I should see each two rows of two members with their name, photo, and social media links.

# AC 
 **WHEN** the page loads
**THEN** four cards should load with each member's name, photo, and social media links
**AND** able to click on links to other social websites.

# Dev Notes
* Create member.html if not already and open main.js
* Be sure to link main.js to member.html
* Create `memberCardBuilder` function that loops through the members array and prints each member's information to a card that prints to the DOM -- use `printToDom`
* Use Bootstrap grid to place them two per row -- center the rows

**Comment by zoeames** [comment]
Array Data - #19
