### ISSUE TITLE
Tour: Loop

### ISSUE THREAD

**Issue by maggieisgreene** [nss-evening-cohort-10/foundations-group-project-huggy-bears#11]
* card layout should have an image on the left and text reflecting location, date, and time to the right of the image (reflected in the images)
* as with other pages, nav bar should rest at top, footer at bottom
* nav bar should reflect that page is currently on Tours by making option bold
* it would be legit if the cards cascaded as they appeared from top to bottom
* bonus feature: a sort option by place.

*

**Comment by gseals** [comment]
bootstrap horizontal

https://getbootstrap.com/docs/4.3/components/card/#horizontal

**Comment by gseals** [comment]
bootstrap card

https://getbootstrap.com/docs/4.3/components/card/#example

**Comment by gseals** [comment]
C:\Users\1026GS~1\AppData\Local\Temp\26\MedicatTemp\994657.JPG

**Comment by gseals** [comment]
![tours](https://user-images.githubusercontent.com/52087296/64974797-2aa7f600-d873-11e9-817b-fe50cb38b937.png)
