### ISSUE TITLE
Jams -- Album Cards Loop

### ISSUE THREAD

**Issue by maggieisgreene** [nss-evening-cohort-10/foundations-group-project-huggy-bears#12]
# User Story
As a user, when the Jams page loads, I will see all the albums done by the  Huggy Bears displayed on the page as cards, with two buttons underneath . One button will be labeled `Buy` and the other  will be labeled `Spotify`. 
The` Buy` button when clicked will route the user to https://music.amazon.com.
The `Spotify` button when pressed will go to the Spotify album.

# AC 
**WHEN** the user selects the Jams option on the navbar
**THEN** the webpage loads and reflects the user story 

# Dev Notes
- Use a for loop title jamsAlbumBuilder to print to dom the album cards styled with bootstrap
- The cards will be an image of the album cover in its entirety 
- as with other pages, nav bar should rest at top, footer at bottom as well
- nav bar should reflect that page is currently on Jams* by making option bold in jams.html
- The buttons used will be used from bootstrap (colors of buttons TBD)

**Comment by rarceneaux** [comment]
https://getbootstrap.com/docs/4.3/components/buttons/#examples

**Comment by zoeames** [comment]
for data use #17
