### ISSUE TITLE
Setup

### ISSUE THREAD

**Issue by maggieisgreene** [nss-evening-cohort-10/foundations-group-project-huggy-bears#13]
# User Story

As a developer, I should create a README.md and push to github repo. I should switch to setup branch and create an index.html, main.css, and main.js, ensure css and js are linked correctly to index, link bootstrap to index, and set default font in the index and css font-family as Roboto.

# AC  

**WHEN** we setup index.html
**THEN** we link main.css, main.js, bootstrap, and google fonts to the index
**AND** set the font-family in main.css for the body of the whole webpage to Roboto

# Dev Notes
* Create index.html, main.css, and main.js
* Link stylesheet and javascript in index.html
* Link latest version of Bootstrap
* Set default font as Roboto

**Comment by gseals** [comment]
Roboto font

https://fonts.google.com/specimen/Roboto?selection.family=Roboto:400,400i,700,700i
