### ISSUE TITLE
All -- printToDom Function

### ISSUE THREAD

**Issue by gseals** [nss-evening-cohort-10/foundations-group-project-huggy-bears#14]
# User Story 

As a user, I should be able to load each page without hiccup and the data should appear without flaw.

# AC

**WHEN** pages load
**THEN** JavaScript should communicate data to HTML
**AND** create the content on the page

# Dev Notes
* each JavaScript loop that is run, we will use the same printToDom to communicate data from JavaScript to the DOM
* use this printToDom format:
```
const printer = (toPrint, divId) => {
  document.getElementById(divId).innerHTML = toPrint
}
```

**Comment by zoeames** [comment]
this doesn't need to be a separate ticket
