### ISSUE TITLE
Home -- Main Header

### ISSUE THREAD

**Issue by maggieisgreene** [nss-evening-cohort-10/foundations-group-project-huggy-bears#15]
# User Story
As a user, I should see a main header that says Huggy Bears in the center at the top of the site -- on every page.

# AC
**WHEN** the page loads
**THEN** you should see a main header that says Huggy Bears
**AND** it should be centered
**AND** styled with Monoton Google Font.

# Dev Notes
* Open index.html and main.css
* Create h1 that says `Huggy Bears`
* Link Monoton Google Font in the index.html -- linked below 
* Style the header with Monoton
* Center header using Bootstrap Flex

**Comment by gseals** [comment]
Monoton font

https://fonts.google.com/specimen/Monoton

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/64912421-aaf41d00-d6f4-11e9-8169-d9c66014b6ca.png)
