### ISSUE TITLE
Home -- Magazine Review

### ISSUE THREAD

**Issue by maggieisgreene** [nss-evening-cohort-10/foundations-group-project-huggy-bears#16]
# User Story
As a user, I should see a magazine review underneath the main image on the home page.

# AC
**WHEN** the page loads
**THEN** a paragraph tag with a magazine review should appear
**AND** it should be underneath the photo carousel on the main page
**AND** it should be centered.

# Dev Notes
* Open index.html -- begin code after carousel code
* Create paragraph tag and insert magazine review text -- see comments for text
* Use Bootstrap Flex to center the text

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/65004308-8ef1a680-d8c1-11e9-9daf-03e8c3380fa0.png)

**Comment by rarceneaux** [comment]
👍
