### ISSUE TITLE
Jams -- Album Array

### ISSUE THREAD

**Issue by rarceneaux** [nss-evening-cohort-10/foundations-group-project-huggy-bears#17]
# User Story

As a develop, I should see an array of objects containing the album name, album cover, and list of songs.

# AC

# Dev Notes

* The data that will be used is as follows:
``` 
[
   {
      albumName: 'test song1',
      image:'imgLinkHere1',
      songs: ['test song1'], ['test song 2'], ['test song 3']
   }
];
```

**Comment by zoeames** [comment]
will be used as part of #12
