### ISSUE TITLE
Members -- Array

### ISSUE THREAD

**Issue by maggieisgreene** [nss-evening-cohort-10/foundations-group-project-huggy-bears#19]
# User Story
As a developer, I should see an array of objects for each member including name, image, socialOne, and socialTwo.

# AC
--Not Available--

# Dev Notes 
* Open main.js
* Create an array of objects called `members` 
* Inside of each object define name, image, socialOne, and socialTwo for each member
```
const members = [
{
name: 'Maggie',
image: 'insert link',
socialOne: 'Twitter link',
socialTwo: 'Instagram link'
}
]
```

**Comment by zoeames** [comment]
this will be used as part of #10
