### ISSUE TITLE
Members page image

### ISSUE THREAD

**Issue by gseals** [nss-evening-cohort-10/foundations-group-project-huggy-bears#2]

**Comment by maggieisgreene** [comment]
![image](https://user-images.githubusercontent.com/54197223/64911769-8e9fb280-d6eb-11e9-998e-e3f733827600.png)

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/64912844-aaf71b80-d6fa-11e9-97be-1a1a67b586b4.png)
