### ISSUE TITLE
Tour -- Card Layout

### ISSUE THREAD

**Issue by gseals** [nss-evening-cohort-10/foundations-group-project-huggy-bears#20]
# User Story

As a user, I should see upcoming tour dates and locations listed with an image of the city the date is occurring 

# AC

**WHEN** the page loads
**THEN** upcoming tour location and dates should appear
**AND** an image should appear to the left of a styled card
**AND** this data comes from the tour array
**AND** is sorted through using the loop we created

# Dev Notes

* use the commented bootstrap card and format to reflect the commented mock up
* the blank image should be an image of the city of the tour

**Comment by gseals** [comment]
bootstrap horizontal

https://getbootstrap.com/docs/4.3/components/card/#horizontal

**Comment by gseals** [comment]
bootstrap card

https://getbootstrap.com/docs/4.3/components/card/#example

**Comment by gseals** [comment]
![tours](https://user-images.githubusercontent.com/52087296/64974797-2aa7f600-d873-11e9-817b-fe50cb38b937.png)

**Comment by zoeames** [comment]
combined with #28
