### ISSUE TITLE
Tour -- Array

### ISSUE THREAD

**Issue by gseals** [nss-evening-cohort-10/foundations-group-project-huggy-bears#21]
# User Story

As a developer, I should create an array of tour data that populates into a bootstrap formulated card.

# AC
**WHEN** I create this data
**THEN** it should reflect tour data
**AND** this encapsulates image of the city being visited
**AND** city and state of performance
**AND** date of performance

# Dev Tools
* this data will pull from the js file and apply to the tour.html file
* format for array data:

```
const upcomingTours = [
{
cityImage: 'image goes here',
cityAndState:  'city & state',
date: 'date of visit'
}
]
```

* choose four tour cities and place city and state in the appropriate location in the array
* select images to signify the cities
* select dates to visit the cities

**Comment by zoeames** [comment]
will be used in #28
