### ISSUE TITLE
Jams -- Buy Button

### ISSUE THREAD

**Issue by rarceneaux** [nss-evening-cohort-10/foundations-group-project-huggy-bears#24]
# User Story

As a user I will see the buy button below the album image on the card.
When click on it will take them to amazon website.

# AC

**WHEN** the buy button is displayed on the page
**THEN** the buy button takes user to amazon.com on click

# Dev Notes

* add event listener listens to the click event on the buy button that will route user to www.amazon.com

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/65005645-26f18f00-d8c6-11e9-96e6-6144abe95bcf.png)

**Comment by rarceneaux** [comment]
This was done on Spotify Card as all it was to do was drop in <a> on each
