### ISSUE TITLE
Jams -- Spotify Button

### ISSUE THREAD

**Issue by rarceneaux** [nss-evening-cohort-10/foundations-group-project-huggy-bears#25]
# User Story
As a user I will see the Spotify button below the album image on the card.
When clicked on it will take the user to Spotify website where they have the option to play the song.

# AC
**WHEN** the Spotify button is displayed on the page
**THEN** the Spotify button takes user to Spotify website on click where the user has the option to play a list of songs.

# Dev Notes
* add event listener listens to the click event on the Spotify button that will play randomly from a list of three songs

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/65005640-248f3500-d8c6-11e9-9438-90cfc939b69f.png)
