### ISSUE TITLE
Jams -- Styling

### ISSUE THREAD

**Issue by rarceneaux** [nss-evening-cohort-10/foundations-group-project-huggy-bears#26]
# User Story 
As a user, I will see the album cards displayed on the page two per row
The buy button will be green with the word BUY in white text
The Spotify button will be in blue with the word Spotify in white text

---
# AC

**WHEN** cards appear on the page 2 in a row in flex
**THEN** the buy Button is green , with white text spelling BUY
**AND** the Spotify Button is blue, with white text spelling Spotify

# Dev Notes

- use  grid d-flex to display the cards on the page 
- use bootstrap buttons as template for buttons

---

**Comment by rarceneaux** [comment]
Buy btn background-color 3D6F66
Spotify btn background-color 0A7798

**Comment by zoeames** [comment]
this should be done as items are finished  - style the buttons and cards as you go
