### ISSUE TITLE
Home -- Previous Tour Stops Array

### ISSUE THREAD

**Issue by maggieisgreene** [nss-evening-cohort-10/foundations-group-project-huggy-bears#27]
# User Story
As a developer, I should see an array of objects called `prevTour` with previous tour information: image, city, and date.

# AC 
-- Not available --

# Dev Notes
* Open main.js
* Create an array of objects called `prevTour`
* Inside of each object define image, city, and date for each previous tour
```
const members = [ 
{
image: 'insert link', 
city: 'city name', 
date: 'date' 
}
]
```

**Comment by zoeames** [comment]
this will be used as part of #9
