### ISSUE TITLE
Tour -- Loop

### ISSUE THREAD

**Issue by gseals** [nss-evening-cohort-10/foundations-group-project-huggy-bears#28]
# User Story

As a user, I should see cards printed with information regarding our tour from the loop

# AC

**WHEN** the page loads
**THEN** the information stored in our tour array should appear
**AND** the layout should reflect the cards we've chosen form bootstrap

# Dev Notes
* utilize a for loop within a function to roll through data
* print them to the cards laid out in earlier ticket
* Create `tourLoopBuilder` function that loops through the upcomingTours array and prints each tour location information to a card that prints to the DOM -- use `printToDom`
* Use Bootstrap grid to place them one per row -- center the rows

**Comment by zoeames** [comment]
Data in #21

**Comment by zoeames** [comment]
see layout in #20
