### ISSUE TITLE
Tour (upcoming concerts) page image

### ISSUE THREAD

**Issue by gseals** [nss-evening-cohort-10/foundations-group-project-huggy-bears#3]

**Comment by yitbarekgitore** [comment]
![image](https://user-images.githubusercontent.com/22806140/64911715-ee498e00-d6ea-11e9-883d-23d79a9ce448.png)

**Comment by ygitore** [comment]
![image](https://user-images.githubusercontent.com/22806140/64911794-f35b0d00-d6eb-11e9-8894-52a904273dcb.png)

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/64912846-bfd3af00-d6fa-11e9-8d0f-85317915af08.png)
