### ISSUE TITLE
Footer -- Social Media Links

### ISSUE THREAD

**Issue by maggieisgreene** [nss-evening-cohort-10/foundations-group-project-huggy-bears#6]
# User Story

As a user, I should see a footer at the bottom of every page containing social media links (Facebook, Instagram, Twitter, Youtube)

# AC 
 **WHEN** the page loads
**THEN** a footer should appear
**AND** it should allow users to find us on social media platforms

# Dev Notes
* Open index.html and main.js
* Create footer element with four anchor tags inside 
* Add appropriate links to each anchor tag to link Facebook, Youtube, Instagram, and Twitter
* Style the anchor tags with FontAwesome -- match color theme

**Comment by gseals** [comment]
![image](https://user-images.githubusercontent.com/52087296/64912579-163eee80-d6f7-11e9-8ac0-fa9c28e281c7.png)
