### ISSUE TITLE
Home -- Previous Tour Stops Loop

### ISSUE THREAD

**Issue by maggieisgreene** [nss-evening-cohort-10/foundations-group-project-huggy-bears#9]
# User Story
As a user, I should see two rows with three images with a city and date underneath.

# AC  
**WHEN** the page loads
**THEN** I should see six cards 
**AND** each card should have an image, city name, and date
**AND** there should be two rows with three cards in each
**AND** the cards should be styled to have space around each side.

# Dev Notes
* Open index.html 
* Create `prevTourCardBuilder` function that loops through `prevTour` array and prints each previous tour information to a card that prints to the DOM -- use printToDom
* To style the cards use Bootstrap grid to place them three per row -- center the rows with equal space around each card -- there should be six elements printing only!

**Comment by zoeames** [comment]
Data in #27
